[profile.default]
src = 'src'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path  = 'forge-cache'
auto_detect_solc = true
optimizer = true
optimizer_runs = 200
via_ir = false
# debug revert strings looks experimental and fails the CI because of an unexpected error.
revert_strings = "default"
names = true
sizes = true

[profile.default.fuzz]
runs = 1024

[profile.production.fuzz]
runs = 256

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
